### ISSUE TITLE
安装完进入后台，看不到菜单

### ISSUE THREAD

**Issue by kikij11** [Vpay-Collection/VPay#1]
![image](https://user-images.githubusercontent.com/42658898/61508918-b392e480-aa1e-11e9-921a-fcf16018d568.png)

**Comment by kikij11** [comment]
php5.6看不到后台菜单
php7.0可以看到菜单，有个问题，就是微信二维码上传不了，支付宝没问题

**Comment by dreamncn** [comment]
微信我过段时间看看，我本来只测试了支付宝，支付宝任意金额生成太好用了，嘻嘻

**Comment by uoboy** [comment]
请问一下各位朋友，扫描付款正常了，就是回调不了，后台订单没有成功
