### ISSUE TITLE
远程服务器不认可？ 苍天饶过我吧！

### ISSUE THREAD

**Issue by eshao2018** [Vpay-Collection/VPay#10]
调试了一下午一直是 远程服务器不认可？另外异步回调是要确认订单这步操作吗？

**Comment by dreamncn** [comment]
这是由于异步回调接口没有正确返回数据所致。
如果正确响应，请返回如下数据：
```
{"state":0,"msg":"okok"}
```
### 付款消息流程如下：

 用户扫码付款 -> 支付宝或者微信推送通知
客户端推送付款信息到服务器 -> 服务器验证信息正确性
服务器向异步回调接口发送请求 -> 异步回调接口响应

### 异步回调接口响应流程：
验证消息正确性 -> 向服务器发送订单确认消息（为了避免恶意刷单）
服务器返回确认消息 ->异步接口确认消息无误，进行业务处理
业务处理完毕 ->响应服务器数据

 具体响应内容请参考`demo/notify.php`
另外，我已经在demo中放置了封装好的工具类`Vpay`，可以直接实例化使用，不需要自己写接口调用。工具类所有文件为`demo\lib`

**Comment by eshao2018** [comment]
好的谢谢，不过还是希望大佬有空辛苦写下开发文档。
