### ISSUE TITLE
同时创建订单付款金额没有递增

### ISSUE THREAD

**Issue by eshao2018** [Vpay-Collection/VPay#11]
同时创建订单付款金额没有递增 同一ip和不同ip都测试了实际付款金额没有递增，当有支付的情况下，系统把支付信息返回给了id最小的那个，比如同一时间2020-03-16 12:16:54创建了两笔订单数据库里面记录生成两条记录id89 和99 实际当有人付款系统返回给了89这个订单，我看原作者的是系统只要有一笔未支付的订单当生成第二笔相同金额的订单时，金额就会发生递增或递减，恳请大佬修复下

**Comment by dreamncn** [comment]
已修复，相关修改文件请看[这里](https://github.com/dreamncn/VPay/commit/e0dfe015be37306b477ab1e896e44ca8c80110f3)

**Comment by eshao2018** [comment]
好的
