### ISSUE TITLE
金额递增问题

### ISSUE THREAD

**Issue by eshao2018** [Vpay-Collection/VPay#12]
上传覆盖了最新的 但是金额递增还没生效，但我测试你的demo就可以

**Comment by dreamncn** [comment]
建议检查以下内容：
1、数据库 pay_settings  vkey值为Payof的对应的vvalue值是否为1
2、检查Order.php 第487行变量 intval($payQf) === Config::PayIncrease

**Comment by eshao2018** [comment]
值是等1 487行的判断也没问题

**Comment by dreamncn** [comment]
既然逻辑没问题，那应该不是我的代码的问题
建议检查是否使用了缓存器之类的缓存机制，如有关闭即可。
