### ISSUE TITLE
请问老师，支付系统搭建好了，扫描支付成功，回调不了，后台订单没显示成功，回调地址设置正确和你所描述一致，请问什么问题导致回调不正常

### ISSUE THREAD

**Issue by uoboy** [Vpay-Collection/VPay#13]
请问老师，支付系统搭建好了，扫描支付成功，回调不了，后台订单没显示成功，回调地址设置正确和你所描述一致，请问什么问题导致回调不正常

**Comment by dreamncn** [comment]
请提供日志文件：`protected/logs`

**Comment by uoboy** [comment]
[2020-03-17 03:42:15][debug] 225
[2020-03-17 09:09:56][debug] 17737
[2020-03-17 11:34:39][debug] 26421
[2020-03-16 21:32:06][debug] 148579

**Comment by dreamncn** [comment]
日志无异常
后台显示`订单已确认`即为付款成功

**Comment by uoboy** [comment]
支付宝扫码付款错误，提示没未注册账号或没激活

**Comment by uoboy** [comment]
微信付款完，后台没有显示已支付，都是等到时间就显示过期了

**Comment by uoboy** [comment]
支付完都是显示待支付，或者过期

**Comment by uoboy** [comment]
麻烦老师帮帮忙了

**Comment by dreamncn** [comment]
支付宝错误是您自己支付宝的问题
微信支付问题参考以下解决方案：
1、请检查访问日志（一般服务器会自动记录，具体方法自行百度），确认是否有 `您的域名/apppush`访问记录
2、请确认微信客户端已经按照要求开启微信支付通知
3、请确认V免签客户端已经正常运营并且监听
4、尝试将V免签客户端更新到最新版本
5、如若还是不能监听，请反馈到V免签app作者处

**Comment by uoboy** [comment]
谢谢老师

**Comment by uoboy** [comment]
> 支付宝错误是您自己支付宝的问题
> 微信支付问题参考以下解决方案：
> 1、请检查访问日志（一般服务器会自动记录，具体方法自行百度），确认是否有 `您的域名/apppush`访问记录
> 2、请确认微信客户端已经按照要求开启微信支付通知
> 3、请确认V免签客户端已经正常运营并且监听
> 4、尝试将V免签客户端更新到最新版本
> 5、如若还是不能监听，请反馈到V免签app作者处

请老师帮忙写个接口和云赏那个打赏视频支付和你平台接入需要多少酬劳？
