### ISSUE TITLE
如何让金额自动递减？

### ISSUE THREAD

**Issue by fakers777** [Vpay-Collection/VPay#15]
不是金额要自动递减吗
如何设置能自动递减啊？
现在金额不变呢。

**Comment by dreamncn** [comment]
金额递减，在设置部分，区分方式

**Comment by fakers777** [comment]
比如上传10.0,9.99 9.98的二维码， 然后付款金额在10的时候会自动生成不重复的金额吗？
设置已经是自动递减了。

**Comment by dreamncn** [comment]
是的
具体使用参考 https://pay.dreamn.cn <https://pay.dreamn.cn/>
本站设置的自动递增

**Comment by fakers777** [comment]
在Order.php的getPayPic()函数中，取二维码用的是price，没有用到realprice啊，你的这个网站也没有递减呢？，难道我看错了吗，请指教
        //第一波取二维码(支付宝自动)结束，看看有没有成功
        if ($payUrl === "") {

            $pay = new PayCode();

            $_payUrl = $pay->getCodeOnly($this->price, $this->type);//根据金额取得二维码

            if ($_payUrl)$payUrl = $_payUrl['pay_url'];//存在该金额的二维码
            $this->isAuto=false;
        }

**Comment by dreamncn** [comment]
为了避免恶意刷取最低金额，所以在同一个浏览器下同一时间段提交的支付请求会把上一个支付关闭

Order.php中有一个获取真实支付金额的函数，不是getPayPic，这个函数是为了根据金额获取二维码

**Comment by fakers777** [comment]
这个算是最完善的收款系统了，只是一直没地方用，谢谢
