### ISSUE TITLE
能不能加个多用户的功能

### ISSUE THREAD

**Issue by jihuoxia** [Vpay-Collection/VPay#16]
能不能加个多用户的功能啊
就是一个免签后台对应多个站点，每个站点不同的收款码

**Comment by dreamncn** [comment]
多站点功能目前是有的，后台-应用管理部分

**Comment by jihuoxia** [comment]
> 多站点功能目前是有的，后台-应用管理部分
不同的应用对应不同的人的收款码这个目前没有这个功能吧

**Comment by dreamncn** [comment]
这个恐怕无法实现，客户端部分无法支持，无法区分收款信息是来自哪个人的微信或者支付宝

**Comment by jihuoxia** [comment]
那能不能通过多用户的形式来实现，比如用户可以注册，或者后台可以手动添加用户，每个用户登录后台可以添加应用和收款码，这样来实现每个应用对应单独的收款码

**Comment by dreamncn** [comment]
无法实现，这个应用的初衷就是个人收款，无法进行多人收款

**Comment by fakers777** [comment]
@jihuoxia 部署2个网站就行了，或者一个网站部署2套系统

**Comment by fakers777** [comment]
@jihuoxia 应该能实现，就是收款的时候金额要整个系统考虑不要重复，然后根据金额来确定哪个用户的，要改数据库结构

**Comment by dreamncn** [comment]
无法实现的，如果允许每个上传自己的二维码就无法让客户端一对一通知，并且会降低系统的支付效率
