### ISSUE TITLE
有没有开发对接的API文档啊

### ISSUE THREAD

**Issue by jihuoxia** [Vpay-Collection/VPay#17]
有没有开发对接的API文档啊

**Comment by dreamncn** [comment]
目前暂时没有，可以暂时参考demo吧
我有空补上文档



---原始邮件---
发件人: "jihuoxia"<notifications@github.com&gt;
发送时间: 2020年4月8日(周三) 下午4:57
收件人: "dreamncn/VPay"<VPay@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dreamncn/VPay] 有没有开发对接的API文档啊 (#17)




 
有没有开发对接的API文档啊

**Comment by huangfengye** [comment]
+1
确实挺需要API文档的。。。
我之前对接了原版V免签到ZFAKA的，但是现在发现用不了你的修改版。
https://github.com/huangfengye/VmqForZfaka

**Comment by dreamncn** [comment]
😂😂我尽量加上开发文档



---原始邮件---
发件人: "huangfengye"<notifications@github.com&gt;
发送时间: 2020年4月8日(周三) 晚上7:39
收件人: "dreamncn/VPay"<VPay@noreply.github.com&gt;;
抄送: "Dreamn"<573658513@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [dreamncn/VPay] 有没有开发对接的API文档啊 (#17)




 
+1
 确实挺需要API文档的。。。
 我之前对接了原版V免签到ZFAKA的，但是现在发现用不了你的修改版。
 https://github.com/huangfengye/VmqForZfaka

**Comment by dreamncn** [comment]
目前正在撰写，请等待一段时间https://doc.dreamn.cn/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/
