### ISSUE TITLE
金额递减还是有问题呢

### ISSUE THREAD

**Issue by fakers777** [Vpay-Collection/VPay#18]
![121211](https://user-images.githubusercontent.com/33420910/78790608-5b06db80-79e1-11ea-9e8c-2af37e15f3e8.png)
感觉还是有bug ,temp表里面没有数据,会把上一次的数据清除掉,导致入库了多个一样的金额

**Comment by dreamncn** [comment]
你别感觉了，你上手试试...

**Comment by fakers777** [comment]
试了，不同客户端支付同样金额，金额还是没有递减

**Comment by dreamncn** [comment]
请详细描述bug发生的情况，要能让我复现出来

**Comment by dreamncn** [comment]
找到问题了，tmp数据表字段类型修改为bigint即可，我本地数据库已经修改了，但是忘了上传
