### ISSUE TITLE
还要不要thinkphp的伪静态？？

### ISSUE THREAD

**Issue by huangfengye** [Vpay-Collection/VPay#2]
还要不要thinkphp的伪静态？？

**Comment by dreamncn** [comment]
不需要，自带apache伪静态文件

**Comment by huangfengye** [comment]
大佬，我用宝塔的Nginx

**Comment by dreamncn** [comment]
宝塔有apache伪静态转nginx工具，一共有两个伪静态文件，根目录/.htaccess和protected/.htaccess

**Comment by uoboy** [comment]
请问各位朋友，付款正常了，就是回调不了，后台订单没有成功，跪求解答
