### ISSUE TITLE
获取的二维码不对

### ISSUE THREAD

**Issue by fakers777** [Vpay-Collection/VPay#22]
![image](https://user-images.githubusercontent.com/33420910/79141781-0900f400-7ded-11ea-9ae2-137fd2bf65f9.png)

获取的二维码使用的是price,而不是real_price,二维码显示和实际金额不符合

**Comment by dreamncn** [comment]
二维码取得是正确的.
无法正确响应的原因是数据库字段类错误
将tmp数据表字段timeout类型修改为bigint即可
这个bug将在下个版本进行修复

**Comment by fakers777** [comment]
不是，你这这个获取二维码的函数，需要获取realprice对应的二维码（有固定金额），比如，价格0.1 ，实际需要支付0.11，那需要获取0.11对应的二维码啊

**Comment by dreamncn** [comment]
哦，好像是这个问题，感谢提醒
