### ISSUE TITLE
店员通知的消息无法响应

### ISSUE THREAD

**Issue by fakers777** [Vpay-Collection/VPay#23]
店员通知消息无法响应吗

**Comment by dreamncn** [comment]
店员通知，请参考此处https://doc.dreamn.cn/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/%E6%94%B6%E6%AC%BE%E8%B4%A6%E6%88%B7%E8%AE%BE%E7%BD%AE?id=%e4%bd%bf%e7%94%a8%e5%ba%97%e5%91%98%e6%94%b6%e6%ac%be <https://doc.dreamn.cn/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/%E6%94%B6%E6%AC%BE%E8%B4%A6%E6%88%B7%E8%AE%BE%E7%BD%AE?id=%E4%BD%BF%E7%94%A8%E5%BA%97%E5%91%98%E6%94%B6%E6%AC%BE>

**Comment by fakers777** [comment]
这些我都设置好了，使用原来的vmqphp程序 可以正常通知并显示支付完成。使用你的程序显示未付款

**Comment by fakers777** [comment]
是有通知，但是服务器没有处理通知

**Comment by dreamncn** [comment]
这不应该啊，我这个和vmqphp使用的是同一套验证逻辑
是不是伪静态没有配置？

**Comment by fakers777** [comment]
已经OK
