### ISSUE TITLE
相同金额在同一时间内不会增加金额

### ISSUE THREAD

**Issue by lelele168** [Vpay-Collection/VPay#24]
相同金额在同一时间内不会增加金额，前一单是1.00，再创建时也是1.00，有时候会把上一个1.00的订单直接显示成订单已过期，系统后台是设置了相同金额增加0.01的，但是程序并没有执行

**Comment by dreamncn** [comment]
tmp数据表timeout字段类型修改为bigint即可,最近忙，没空更新

**Comment by lelele168** [comment]
那个demo回调验证那里也有点bug，希望有时间能修改下

**Comment by dreamncn** [comment]
好
