### ISSUE TITLE
新版本2.2出现了请求上传接口出现异常问题

### ISSUE THREAD

**Issue by lelele168** [Vpay-Collection/VPay#26]
在系统设置里面传无金额二维码时出现了“请求上传接口出现异常”错误，微信和支付宝有金额二维码也是只显示处理中，页面一直没有识别二维码内容

**Comment by dreamncn** [comment]
已修复，具体更新修改文件请参考https://github.com/dreamncn/VPay/commit/1810e8d86e5a3a05a148a11a4b3e13ba77b98723
