### ISSUE TITLE
后台设置的logo显示问题

### ISSUE THREAD

**Issue by lelele168** [Vpay-Collection/VPay#28]
上传后显示是刚传的logo，但是一刷新就会显示成默认的logo

**Comment by dreamncn** [comment]
请检查 /i/img/qrLogo.png是否有可写权限
上传完成后请检查是否真的修改了该文件，避免浏览器缓存影响

**Comment by lelele168** [comment]
文件是有0666权限的，也是真实写入了，就是后台显示的logo和它不一致

**Comment by dreamncn** [comment]
那就是缓存问题了，你可以使用浏览器的隐私模式重新登录，或者直接打开图片URL刷新几次
