### ISSUE TITLE
能不能后台增加过期订单的显示按钮

### ISSUE THREAD

**Issue by lelele168** [Vpay-Collection/VPay#29]
原程序的这个功能挺好的，防止用户在超时后支付，但是后台找不到相应的订单，还要去收款助手一个个的找出来，再和原过期的订单补单来完成这操作

**Comment by dreamncn** [comment]
这个功能一直都有，没有删减

**Comment by dreamncn** [comment]
![og9faW](https://cdn.jsdelivr.net/gh/dreamncn/picBed/og9faW.png)

**Comment by lelele168** [comment]
超时支付的没有，就是在超过有效期支付的订单，或者支付错金额的订单

**Comment by dreamncn** [comment]
这个功能不应该有，他会导致整个系统的订单混乱，举个例子：
A用户点开一个1元的支付页面，并且扫码了，但是没在有效期内支付，后台标记为过期状态
然而B用户此时也点开了1元的支付页面，并且支付了金额
那么此时系统应该认为这个1元是由A用户支付还是B用户的超时支付？
我们整个系统就是按照有效期内订单金额来区分用户的，这样做违背初衷。

**Comment by lelele168** [comment]
这也是个问题，但是在临近的时间内创建的订单实际支付金额不要一致就好了，1元的关了，下一个是1.01，下次系统创建1元的订单系统在3分钟后，或者创建到5个订单后再循环这些已经关闭的金额

**Comment by lelele168** [comment]
一个支付1元，订单过期了，第二个支付的订单一定是1.01的，就算超时了，系统后台显示对应的金额超时支付的，这样也方便手工补单，第二个人如果是支付1元，那也是订单不会成功匹配到，但是后台显示这两条记录，这样也能清晰地补单

**Comment by dreamncn** [comment]
超时与错付这两种不在考虑范围内的，因为他们不按照规则来。
他们本身就是对规则的一种破坏。

**Comment by lelele168** [comment]
所以后台可以把没匹配到的订单也显示出来，方便核对补单，毕竟支付的都是大爷，ε=(´ο｀*)))唉

**Comment by dreamncn** [comment]
没匹配到的订单并没有隐藏~一般显示为过期，你可以通过查看详情来判断参数中是否携带了某个用户的具体信息，然后判断订单

如果说显示无订单收款的话，会导致很多不必要的重复订单，而且无订单收款也无法补单，因为他没有匹配到任何订单

**Comment by lelele168** [comment]
无订单收款能不能独立文件出来显示接收下，这样方便点

**Comment by lelele168** [comment]
就是要通过无订单收款来匹配那些原来创建的订单来补原来过期的订单的

**Comment by dreamncn** [comment]
个人认为这是多余的操作，因为系统是无法匹配到这些订单的
如果你需要，请在
/protected/controller/index/AppController.php第79行添加处理逻辑

**Comment by lelele168** [comment]
处理的逻辑能发下吗，(꒦_꒦)

**Comment by dreamncn** [comment]
```php
  if (!$res) {
            $data = array(
                "close_date" => 0,
                "create_date" => time(),
                "is_auto" => 0,
                "notify_url" => "",
                "order_id" => "无订单转账",
                "param" => "无订单转账",
                "pay_date" => 0,
                "pay_id" => "无订单转账",
                "pay_url" => "",
                "price" => $price,
                "really_price" => $price,
                "return_url" => "",
                "state" => 1,
                "type" => $type,
                "appid" => 0
            );

            $ord->Insert($data);

            exit(json_encode(array("code" => 0, "msg" => "")));

        }
```

**Comment by lelele168** [comment]
按此代码添加修改后，后台没有相应数据

**Comment by lelele168** [comment]
if (!$res) {
            $data = array(
                "close_date" => 0,
                "create_date" => time(),
                "is_auto" => 0,
                "notify_url" => "",
                "order_id" => "无订单转账",
                "param" => "无订单转账",
                "pay_date" => 0,
                "pay_id" => "无订单转账",
                "pay_url" => "",
                "price" => $price,
                "really_price" => $price,
                "return_url" => "",
                "state" => 1,
                "type" => $type,
                "appid" => 0
            );

            $ord->Insert($data);

            exit(json_encode(array("code" => 0, "msg" => "")));

        }

        $tmp = new Temp();

        $tmp->DelByOid($res["order_id"]);//删除临时表

        $ord->ChangeStateByOrderId($res["order_id"], Order::State_Ok, time(), time());//更新订单信息

        echo $ord->Notify($res["order_id"]);

    }


}

**Comment by dreamncn** [comment]
哦，忘了，这是早期的一个代码~
你把Insert改成add

> 2020年5月9日 下午8:37，lelele168 <notifications@github.com> 写道：
> 
> Insert

**Comment by lelele168** [comment]
修改后，正常的订单也不会到账了！！！

**Comment by lelele168** [comment]
if (!$res) {
            $data = array(
                "close_date" => 0,
                "create_date" => time(),
                "is_auto" => 0,
                "paytype" => "",
                "order_id" => "无订单转账",
                "param" => "无订单转账",
                "pay_date" => 0,
                "pay_id" => "无订单转账",
                "pay_url" => "",
                "price" => $price,
                "really_price" => $price,
                "return_url" => "",
                "state" => 1,
                "type" => $type,
                "appid" => 0
            );

            $ord->add($data);

            exit(json_encode(array("code" => 0, "msg" => "")));

        }

        $tmp = new Temp();

        $tmp->DelByOid($res["order_id"]);//删除临时表

        $ord->ChangeStateByOrderId($res["order_id"], Order::State_Ok, time(), time());//更新订单信息

        echo $ord->Notify($res["order_id"]);

    }


}

**Comment by dreamncn** [comment]
不知道你哪里改出问题了，请自行排查。

**Comment by lelele168** [comment]
if (!$res)
{
        $data = array(
            "close_date" => 0,
            "create_date" => time(),
            "is_auto" => 0,
            "paytype" => "",
            "order_id" => "无订单转账",
            "param" => "无订单转账",
            "pay_date" => 0,
            "pay_id" => "无订单转账",
            "pay_url" => "",
            "price" => $price,
            "really_price" => $price,
            "return_url" => "",
            "state" => 1,
            "type" => $type,
            "appid" => 0
        );

        $ord->add($data);

        exit(json_encode(array("code" => 0, "msg" => "")));

    }

和 if (!$res)return;

貌似框架不一样，按前面这样修改后端不能正常接收到数据

**Comment by lelele168** [comment]
根据系统流程，最后排查到protected\model\order.php文件进行了订单数据隔离，无法直接在/protected/controller/index/AppController.php直接插入数据

**Comment by dreamncn** [comment]
不存在数据隔离的说法，谢谢。我刚才查看了一下，新版本移除了add方法，你可以手动在order.php添加
```php
function add($arg){
$this->insert($arg);
}
```
需要自定义功能请自行添加，或查看历史版本自己修改。我没有义务增加这些没必要的功能。
用户的错误不能由我们来买单，如果一个系统还需要人工手动补单，那么他就不应该作为一个系统。
