### ISSUE TITLE
刚刚搞了好久，看了问题原来是运行环境问题。

### ISSUE THREAD

**Issue by ok009** [Vpay-Collection/VPay#3]
刚刚搞了好久，看了问题原来是运行环境问题，感觉windows还是iis环境比较好用，响应速度比APACHE快，望下次整个iis环境的。还有就是貌似作者的监控端也不稳定，权限都给予了，也总是掉线异常！蛋蛋有点疼....

**Comment by dreamncn** [comment]
我不熟悉jsp,jspx...我这边安卓Q挺稳定的...异常是网络不好...

**Comment by dreamncn** [comment]
我不熟悉asp,aspx...我这边安卓Q挺稳定的...异常是网络不好...

**Comment by uoboy** [comment]
请问付款正常了，就是回调不了，后台订单没有成功

**Comment by dreamncn** [comment]
回调失败请检查：
1、是否正确设置回调地址，设置方法请看README
2、程序自带日志功能，请查看`protected/logs`下的日志进行排错

**Comment by dreamncn** [comment]
新的问题，请重提issue，谢谢
