### ISSUE TITLE
内置商城错误

### ISSUE THREAD

**Issue by huangfengye** [Vpay-Collection/VPay#30]
![QQ截图20200104130159](https://i.imgur.com/lM1XJAY.png)
)

**Comment by huangfengye** [comment]
似乎是强制HTTPS导致的。。关闭掉HTTPS后，可以正常生成订单

**Comment by dreamncn** [comment]
文档中有说明，请仔细看文档，谢谢。
![nInucS](https://cdn.jsdelivr.net/gh/dreamncn/picBed/nInucS.png)
