### ISSUE TITLE
后台订单里面的支付时间都是固定的

### ISSUE THREAD

**Issue by lelele168** [Vpay-Collection/VPay#34]
订单支付时间都是1970-01-01 08:00:01  关闭和创建时间这些都没有问题

**Comment by dreamncn** [comment]
下个版本修复。

**Comment by rrkai** [comment]
大佬..开发文档打不开

**Comment by dreamncn** [comment]
> 大佬..开发文档打不开

已更新，https://doc.ankio.net/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/
