### ISSUE TITLE
个人qq的账单如何实现

### ISSUE THREAD

**Issue by t-o-n-y-w** [Vpay-Collection/VPay#37]
如何实现个人qq钱包的监控以及回调呢

**Comment by dreamncn** [comment]
暂时没有考虑QQ的收款。


---原始邮件---
发件人: &quot;t-o-n-y-w&quot;<notifications@github.com&gt;
发送时间: 2020年11月28日(周六) 上午10:52
收件人: &quot;dreamncn/VPay&quot;<VPay@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [dreamncn/VPay] 个人qq的账单如何实现 (#37)




 
如何实现个人qq钱包的监控以及回调呢
 
&mdash;

**Comment by t-o-n-y-w** [comment]
大佬 搞一下啦

**Comment by dreamncn** [comment]
不予以考虑。
