### ISSUE TITLE
今天安装时 到了创建数据库的这步骤 出问题啦！提示 无法连接数据库 之前没有

### ISSUE THREAD

**Issue by t-o-n-y-w** [Vpay-Collection/VPay#38]

**Comment by dreamncn** [comment]
你自己数据库的问题。



---原始邮件---
发件人: "t-o-n-y-w"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 晚上11:45
收件人: "dreamncn/VPay"<VPay@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dreamncn/VPay] 今天安装时 到了创建数据库的这步骤 出问题啦！提示 无法连接数据库 之前没有 (#38)
