### ISSUE TITLE
心跳返回值 为 code 0 msg success  啥情况呢？ 其次 你那个sdk config 8-10 第十行 是 如何填写？ 创建APP 同步回调 异步回调 如何填写？

### ISSUE THREAD

**Issue by t-o-n-y-w** [Vpay-Collection/VPay#39]

**Comment by dreamncn** [comment]
返回success表示心跳正常。
其他问题开发文档写的很清楚，请仔细研读。



---原始邮件---
发件人: "t-o-n-y-w"<notifications@github.com&gt;
发送时间: 2020年12月22日(周二) 中午12:16
收件人: "dreamncn/VPay"<VPay@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dreamncn/VPay] 心跳返回值 为 code 0 msg success  啥情况呢？ 其次 你那个sdk config 8-10 第十行 是 如何填写？ 创建APP 同步回调 异步回调 如何填写？ (#39)
