### ISSUE TITLE
开发文档打不开..二维码上传不了

### ISSUE THREAD

**Issue by rrkai** [Vpay-Collection/VPay#40]
大佬..开发文档的网址打不开.能不能做成本地的啊.
还有二维码也上传不了,出现请求上传接口出现异常.这个玩意能不能也做成本地的啊

**Comment by dreamncn** [comment]
开发文档地址：https://doc.ankio.net/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/
本地的话，自己搭建个本地的服务器就行，接口异常使用浏览器抓包看一下

**Comment by rrkai** [comment]
抓了好像有很多错误..看不懂了..大佬有空麻烦加下Q 78560034呗 有偿问答 哈哈
