### ISSUE TITLE
内置商城的付款选项搞反了

### ISSUE THREAD

**Issue by rrkai** [Vpay-Collection/VPay#41]
内置商城的付款选项搞反了.点支付宝跳转成微信,点微信跳转成支付宝

**Comment by rrkai** [comment]
还有上传无金额二维码的时候,PHP7.3正常,7.4会上传失败

**Comment by rrkai** [comment]
还有监控端状态会异常,就是明明没掉线,一刷新就会显示掉线.
还有支付详情支付时间全部是1970-01-01 08:00:01
还有就是原版的V免签这条修复(因为很多人的服务器时间不准确，因此删除时间校验，不会出现客户端时间错误了)在VPAY上面没修复所以客户端时间跟服务器相差的话就会一直出现订单过期的情况

**Comment by dreamncn** [comment]
过段时间重构新版本，V免签系列准备停止维护了。

**Comment by rrkai** [comment]
> 过段时间重构新版本，V免签系列准备停止维护了。

那大佬到时会兼容现在的V免签么..如果兼容的话 那我就先把项目用VPAY用上.到时再换你的新的..付费用也可以

**Comment by dreamncn** [comment]
不会。新版本比这个好用，如果使用我的sdk的话，迁移起来只要更新sdk就行。
&nbsp;

生活赋予我们一种巨大的和无限高贵的礼品，这就是青春：充满着力量，充满着期待志愿，充满着求知和斗争的志向，充满着希望信心和青春。&nbsp;—— 奥斯特洛夫斯基


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 晚上6:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [dreamncn/VPay] 内置商城的付款选项搞反了 (#41)





  
过段时间重构新版本，V免签系列准备停止维护了。
  
那大佬到时会兼容现在的V免签么..如果兼容的话 那我就先把项目用VPAY用上.到时再换你的新的..付费用也可以
