### ISSUE TITLE
自己做了一個Docker但是数据库连接失败

### ISSUE THREAD

**Issue by simonlkch** [Vpay-Collection/VPay#44]
我起了一個Dockerfile

我用MySql WorkBench 是可以連結到的
但在创建数据库是打入相對的信息後出現数据库连接失败

在检查安装环境頁面上, 我所有的都通過

不知有沒有做一個docker的安裝方法

Dockerfile

`Dockerfile
version: '3'

services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8050:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  mysql:
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
`

<html>
<body>

项目 | 程序所需 | 最佳配置推荐 | 当前服务器
-- | -- | -- | --
PHP伪静态 | 需要 | 需要 | 已配置
操作系统 | 不限 | Linux | Linux
PHP版本 | 7.0 | 7.3 | 7.3.28
附件上传 | 2M | 2M | 2M
磁盘空间 | 12M | 12M | 63193M

目录文件 | 所需状态 | 当前状态
-- | -- | --
protected/tmp | 可写 | 可写
install | 可写 | 可写
/i/img/logo.png | 可写 | 可写

目录文件 | 所需状态 | 当前状态
-- | -- | --
json_decode() | 支持 | 支持
json_encode() | 支持 | 支持
urldecode() | 支持 | 支持
urlencode() | 支持 | 支持
openssl_encrypt() | 支持 | 支持
openssl_decrypt() | 支持 | 支持
file_get_contents() | 支持 | 支持
mb_convert_encoding() | 支持 | 支持
curl_init() | 支持 | 支持

拓展名称 | 所需状态 | 当前状态
-- | -- | --
curl | 支持 | 支持
openssl | 支持 | 支持
gd | 支持 | 支持
json | 支持 | 支持
session | 支持 | 支持
PDO | 支持 | 支持
iconv | 支持 | 支持
hash | 支持 | 支持
mysqli | 支持 | 支持

</body>
</html>

**Comment by t-o-n-y-w** [comment]
SDK怎么使用？

**Comment by dreamncn** [comment]
检查能不能从容器访问外部mysql服务。

**Comment by simonlkch** [comment]
> 检查能不能从容器访问外部mysql服务。

我用外部的MySql WorkBench 是可以連結到的

**Comment by dreamncn** [comment]
你要在容器内部测试。
这个代码应该是没有问题的。
连接失败有几个原因
&nbsp;1.IP或者端口错误
2.数据库服务未启动
3.被防火墙拦截了





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月6日(周二) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dreamncn/VPay] 自己做了一個Docker但是数据库连接失败 (#44)




  
检查能不能从容器访问外部mysql服务。
  
我用外部的MySql WorkBench 是可以連結到的

**Comment by dreamncn** [comment]
上次我忘了说，需要修改根目录的Config.php文件

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
