### ISSUE TITLE
能否加入回调失败后，多次回调的功能

### ISSUE THREAD

**Issue by hillghost86** [Vpay-Collection/VPay#45]
感谢大佬分享的PHP版Vpay。
使用一段时间后，发现偶尔会出现支付成功，服务端也收到了支付推送，但回调失败。订单列表显示“已支付”，这时需要手工补单。
希望大佬能更新个回调失败后，自动补单的功能。类似于支付宝官方支付的二次、三次、多次回调。

**Comment by dreamncn** [comment]
好的

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
