### ISSUE TITLE
咋对接大佬能出个对接Zfaka插件嘛

### ISSUE THREAD

**Issue by ldkiss** [Vpay-Collection/VPay#46]
咋对接大佬能出个对接Zfaka插件嘛

**Comment by dreamncn** [comment]
参考文档&nbsp;
https://doc.ankio.net/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
