### ISSUE TITLE
后台上传二维码提示错误

### ISSUE THREAD

**Issue by ludashi2020** [Vpay-Collection/VPay#49]
![pic](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-17a2be90-3ea0-49c5-bf3b-cdaa9d8159f9/84b56cb9-90a2-4d34-907f-755ae46b4b67.png)

后台上传二维码总是提示接口错误，求大佬指点，谢谢！

**Comment by dreamncn** [comment]
配置伪静态
