### ISSUE TITLE
宝塔搭建不显示验证码

### ISSUE THREAD

**Issue by kikij11** [Vpay-Collection/VPay#5]
![image](https://user-images.githubusercontent.com/42658898/75603229-81467b00-5b07-11ea-942c-e29f9b0a4fc7.png)
不显示验证码，宝塔环境nginx1.17+php7.0+mysql5.6

**Comment by dreamncn** [comment]
1、确保程序运行于根目录
2、请F12查看验证码图片拉取路径是否正确
3、建议更新到最新版本

**Comment by kikij11** [comment]
![image](https://user-images.githubusercontent.com/42658898/75644664-fd62cf00-5c7d-11ea-84b4-ae5a59fc0926.png)

全新安装1.5，登陆界面都显示不了了
![image](https://user-images.githubusercontent.com/42658898/75644698-18354380-5c7e-11ea-99f3-39423eb4d7be.png)

**Comment by dreamncn** [comment]
做好伪静态，直接访问http://pay.187pk.com:88/admin即可
