### ISSUE TITLE
最新版本监控端一直连接不上

### ISSUE THREAD

**Issue by lin-1259** [Vpay-Collection/VPay#51]
作者您好,我下载了最新的源码还有最新的监控端,但是扫码后后台一直是已掉线
![Snipaste_2021-11-08_01-02-38](https://user-images.githubusercontent.com/60593825/140654405-4bf2c785-eb1f-4d3d-afde-6ea3fef234de.png)

心跳返回:
![1636304375796](https://user-images.githubusercontent.com/60593825/140654410-1e66645b-d8d3-4ff5-987f-2830379f79ea.jpg)

请问一下这是什么原因

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
