### ISSUE TITLE
域名绑定错误！

### ISSUE THREAD

**Issue by airansate** [Vpay-Collection/VPay#52]
程序已经提示安装成功了，要访问的时候一直一直提示域名绑定错误
![微信截图_20220106190818](https://user-images.githubusercontent.com/44084033/148373978-2689ba23-b506-4f92-8013-dc786c4a578b.png)
![微信截图_20220106191107](https://user-images.githubusercontent.com/44084033/148374169-56d7e05b-ea7e-4dbf-90d5-d1cd07491be4.png)
！

**Comment by dreamncn** [comment]
检查 config.php中的域名和你访问的域名是否一致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月6日(周四) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dreamncn/VPay] 域名绑定错误！ (Issue #52)




 
程序已经提示安装成功了，要访问的时候一直一直提示域名绑定错误
 
 
 ！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
