### ISSUE TITLE
不支持独角数卡

### ISSUE THREAD

**Issue by hmilya** [Vpay-Collection/VPay#53]
独角数卡支持V免签，大佬的这个增强版签名算法和回调方式跟V免签有区别

**Comment by hmilya** [comment]
大佬抽时间能不能指导下，如何调用独角数卡V免签的接口文件

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
