### ISSUE TITLE
无法正常安装

### ISSUE THREAD

**Issue by U29kaXVt** [Vpay-Collection/VPay#56]
按照README.md的要求配置完毕后，出现以下log，无法进行安装
（域名已隐去）
[2022-02-24 21:18:08][error] [,file:/www/wwwroot/*隐去*/core/error/Error.php,line:185,function:error,file:/www/wwwroot/*隐去*/core/error/Error.php,line:61,function:err,function:appException]TypeError: Typed property app\core\database\sql\sqlExec::$dbData must be array, string used in /www/wwwroot/*隐去*/core/database/sql/sqlExec.php:56

**Comment by dreamncn** [comment]
你应该正确配置数据库



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月24日(周四) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dreamncn/VPay] 无法正常安装 (Issue #56)




 
[2022-02-24 21:18:08][error] [,file:/www/wwwroot/隐去/core/error/Error.php,line:185,function:error,file:/www/wwwroot/隐去/core/error/Error.php,line:61,function:err,function:appException]TypeError: Typed property app\core\database\sql\sqlExec::$dbData must be array, string used in /www/wwwroot/隐去/core/database/sql/sqlExec.php:56
 
以上为log
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by U29kaXVt** [comment]
可是readme.md没提到要在哪配置数据库

**Comment by 5170124555** [comment]
这个项目我盘了10多天了作者能否出一个安装教程

**Comment by 5170124555** [comment]
这个项目加油维持下去后面火

**Comment by 1125951511** [comment]
安装属实搞不明白，求作者大大整个安装教程

**Comment by dreamncn** [comment]
src内容放到网站根目录
配置伪静态
配置config/frame.yml中的域名
然后访问网站安装就行了




教程没空，忙着呢

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月25日(周五) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dreamncn/VPay] 无法正常安装 (Issue #56)




 
安装属实搞不明白，求作者大大整个安装教程
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1125951511** [comment]
搭建之后
![image](https://user-images.githubusercontent.com/100396959/155731094-c488369d-7a30-4941-9e9d-504be16d76e4.png)
安装跳转那里会一直循环倒计时请问这是什么问题

**Comment by 1125951511** [comment]
> 搭建之后 ![image](https://user-images.githubusercontent.com/100396959/155731094-c488369d-7a30-4941-9e9d-504be16d76e4.png) 安装跳转那里会一直循环倒计时请问这是什么问题

这是为什么哇

**Comment by Orenda-Han** [comment]
> src内容放到网站根目录 配置伪静态 配置config/frame.yml中的域名 然后访问网站安装就行了 教程没空，忙着呢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月25日(周五) 下午5:44 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [dreamncn/VPay] 无法正常安装 (Issue #56) 安装属实搞不明白，求作者大大整个安装教程 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

全都按操作做了，确实无法安装，报403错误，伪静态也都核对了，不知道哪里的问题。

**Comment by dreamncn** [comment]
修改db.example.yml为db.yml可正常安装
Duplicate of #57

**Comment by sl818** [comment]
安装成功了，美滋滋
我的安装步骤（用的宝塔面板）：

- 修改伪静态配置
- src文件夹内放入跟目录
- 修改 config/frame.yml文件中的域名为vpay的域名
- 修改 config/db.examle.yml为config/db.yml
- 修改网站运行目录为：public
成功进入到安装引导页面，填写信息后进入后台登陆

不显示登录验证码的问题：

- 宝塔面板-网站设置-配置文件
- 第47行删除jpg、jpeg即可

**Comment by qingxiablog** [comment]
> 安装成功了，美滋滋 我的安装步骤（用的宝塔面板）：
> 
> * 修改伪静态配置
> * src文件夹内放入跟目录
> * 修改 config/frame.yml文件中的域名为vpay的域名
> * 修改 config/db.examle.yml为config/db.yml
> * 修改网站运行目录为：public
>   成功进入到安装引导页面，填写信息后进入后台登陆
> 
> 不显示登录验证码的问题：
> 
> * 宝塔面板-网站设置-配置文件
> * 第47行删除jpg、jpeg即可

大哥，修改frame.yml里哪个域名？localhost》还是127.0.0.1，没整明白修改哪个，求指教

**Comment by dreamncn** [comment]
随便哪个都可以


在 2023年2月21日 ***@***.***> 写道：


安装成功了，美滋滋 我的安装步骤（用的宝塔面板）：
修改伪静态配置 src文件夹内放入跟目录 修改 config/frame.yml文件中的域名为vpay的域名 修改 config/db.examle.yml为config/db.yml 修改网站运行目录为：public
 成功进入到安装引导页面，填写信息后进入后台登陆
不显示登录验证码的问题：
宝塔面板-网站设置-配置文件 第47行删除jpg、jpeg即可
大哥，修改frame.yml里哪个域名？localhost》还是127.0.0.1，没整明白修改哪个，求指教
