### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by dudt** [Vpay-Collection/VPay#57]
按照部署说明
TypeError: Typed property app\core\database\sql\sqlExec::$dbData must be array, string used in /www/wwwroot/*/core/database/sql/sqlExec.php:56

也填写了db.example.yml这个文件

无法正常安装

**Comment by dreamncn** [comment]
Duplicate of #56 
修改db.example.yml为db.yml可正常安装

**Comment by dudt** [comment]
> Duplicate of #56 修改db.example.yml为db.yml可正常安装

修改后可以到安装页面，但是一直显示loading..
![image](https://user-images.githubusercontent.com/19968269/156880376-36660e1f-1b3b-4bb2-9836-57e75ee8ea28.png)

**Comment by dreamncn** [comment]
F12看看是不是js出错了

**Comment by dudt** [comment]
> F12看看是不是js出错了

已解决，重新下载了源码，已经安装成功。谢谢
