### ISSUE TITLE
咨询如何对接彩虹易支付

### ISSUE THREAD

**Issue by WilliamFWJ** [Vpay-Collection/VPay#58]
目前使用的是v2.4
想咨询一下如何对接彩虹易支付
好像很多易支付对接插件没有appid 选项
<img width="978" alt="image" src="https://user-images.githubusercontent.com/35882207/159160143-9893428c-7239-4169-8fc6-3dc258c03a7f.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/35882207/159160244-01db6d7c-b57d-491e-9075-5452784cf8fd.png">

**Comment by dreamncn** [comment]
他们应该有自己的对接插件才对，不应该问我。
