### ISSUE TITLE
升级最新版设置无金额二维码上传没反应

### ISSUE THREAD

**Issue by eshao2018** [Vpay-Collection/VPay#6]
升级最新版设置无金额二维码上传没反应

报错setting:129 Uncaught ReferenceError: getObjectURL is not defined
    at setting:129
    at FileReader.n.onload (upload.js:2)

**Comment by dreamncn** [comment]
已经更新，请下载`1.6版本` 覆盖`/protected/view/admin/main_setting.html`文件
