### ISSUE TITLE
二维码外加文字

### ISSUE THREAD

**Issue by lelele168** [Vpay-Collection/VPay#60]
旧版系统中如何在支付页的二维码底部加上订单号，过期时间那些数据等文字啊    一起拼接成图片和二维码在一起

**Comment by dreamncn** [comment]
旧版不维护了。
可以自己抓一下接口拿到的数据，然后自行渲染就行。

**Comment by lelele168** [comment]
> 旧版不维护了。 可以自己抓一下接口拿到的数据，然后自行渲染就行。

能帮忙修改增加下吗  付费  自己写不明白
