### ISSUE TITLE
新版能否像旧版一样增加微信支付

### ISSUE THREAD

**Issue by imhuimie** [Vpay-Collection/VPay#61]

**Comment by jiaminghai** [comment]
https://gitee.com/lionjohn/Vpay
发现一个PC版监控，采用阿里旺旺和微信电脑版进行监控，但是闭源的，对项目的可持续性不好说。
是不是可以考虑下恢复以前的固定金额二维码收款呢？
![image](https://user-images.githubusercontent.com/61571153/222874424-975bb58b-1a97-4e72-92c0-896bf7b60893.png)

**Comment by dreamncn** [comment]
新的监控方案已经在做了
不需要手机端也不需要PC端，只要在服务端配置一下就能正常挂机监控，不过目前还在测试中。

总共是3套监控方案：
服务端监控：通过配置Cookie的方式，并在后台轮询刷新Cookie进行订单检测。缺点是需要找Cookie，有点是延迟低，稳定性很高。
app端监控：通过客户端上报支付订单信息，网络不好会有延迟。
对接支付宝小微商户：这个认证比较方便，延迟低，缺点就是会收手续费。

目前计划中是 优先采用服务端监控，其次是app监控，最后采用支付宝小微商户。

收款码的话，不再支持定额收款，需要用户手动填入支付金额收款。

区分订单的话，目前有两种方案：
使用不同的订单金额（最通用）
要求用户填入备注信息（只适用于服务端收款）

对于固定金额二维码收款，我个人觉得：
配置比较麻烦，如果需要收款的金额比较多，挨个上传有点费事；
可能会被风控；
支付宝倒是可以进行固定二维码收款，但是ios设备扫码会提示风险，无法付款。

所以基于上面种种原因，不会添加固定二维码收款功能。

**Comment by jiaminghai** [comment]
鼓励一下，加油！

**Comment by jiaminghai** [comment]
> 新的监控方案已经在做了 不需要手机端也不需要PC端，只要在服务端配置一下就能正常挂机监控，不过目前还在测试中。
> 
> 总共是3套监控方案： 服务端监控：通过配置Cookie的方式，并在后台轮询刷新Cookie进行订单检测。缺点是需要找Cookie，有点是延迟低，稳定性很高。 app端监控：通过客户端上报支付订单信息，网络不好会有延迟。 对接支付宝小微商户：这个认证比较方便，延迟低，缺点就是会收手续费。
> 
> 目前计划中是 优先采用服务端监控，其次是app监控，最后采用支付宝小微商户。
> 
> 收款码的话，不再支持定额收款，需要用户手动填入支付金额收款。
> 
> 区分订单的话，目前有两种方案： 使用不同的订单金额（最通用） 要求用户填入备注信息（只适用于服务端收款）
> 
> 对于固定金额二维码收款，我个人觉得： 配置比较麻烦，如果需要收款的金额比较多，挨个上传有点费事； 可能会被风控； 支付宝倒是可以进行固定二维码收款，但是ios设备扫码会提示风险，无法付款。
> 
> 所以基于上面种种原因，不会添加固定二维码收款功能。

也可以考虑下增加PC端监控作为补充，自己有winserver的服务器，挂机方便，刚加了做PC端监控的Q群，PC监听不收费，但是好像没有开源。
http://blog.vsiis.com/65.html

**Comment by dreamncn** [comment]
> > 新的监控方案已经在做了 不需要手机端也不需要PC端，只要在服务端配置一下就能正常挂机监控，不过目前还在测试中。
> > 总共是3套监控方案： 服务端监控：通过配置Cookie的方式，并在后台轮询刷新Cookie进行订单检测。缺点是需要找Cookie，有点是延迟低，稳定性很高。 app端监控：通过客户端上报支付订单信息，网络不好会有延迟。 对接支付宝小微商户：这个认证比较方便，延迟低，缺点就是会收手续费。
> > 目前计划中是 优先采用服务端监控，其次是app监控，最后采用支付宝小微商户。
> > 收款码的话，不再支持定额收款，需要用户手动填入支付金额收款。
> > 区分订单的话，目前有两种方案： 使用不同的订单金额（最通用） 要求用户填入备注信息（只适用于服务端收款）
> > 对于固定金额二维码收款，我个人觉得： 配置比较麻烦，如果需要收款的金额比较多，挨个上传有点费事； 可能会被风控； 支付宝倒是可以进行固定二维码收款，但是ios设备扫码会提示风险，无法付款。
> > 所以基于上面种种原因，不会添加固定二维码收款功能。
> 
> 也可以考虑下增加PC端监控作为补充，自己有winserver的服务器，挂机方便，刚加了做PC端监控的Q群，PC监听不收费，但是好像没有开源。 http://blog.vsiis.com/65.html

PC端的监控原理和服务端差不多，如果我自己搞的话，大概率是命令行版的。

不过可以考虑对接。

**Comment by dreamncn** [comment]
fixed by master branch https://github.com/Vpay-Collection/VPay/tree/master

**Comment by zhjurz** [comment]
> 

不知道大佬您那边开发免挂成功了没  我真的很感兴趣，不知道能否参与内测？

**Comment by dreamncn** [comment]
测试过了，不太问题，下线这个功能了
