### ISSUE TITLE
nginx 伪静态 不行！！！

### ISSUE THREAD

**Issue by wordos** [Vpay-Collection/VPay#67]
nginx 伪静态 不行！！！

**Comment by dreamncn** [comment]
请补充信息：
NGINX配置文件

**Comment by wordos** [comment]
本地使用 phpstudy 测试  访问网站提示：Parse error: syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in D:\PAY\cleanphp\App.php on line 2  

伪静态使用的是：
if ( $uri ~* "^(.*)\.php$") {
rewrite ^(.*) /index.php break;
}

location / {
  try_files $uri $uri/ /index.php?$query_string;
}

**Comment by dreamncn** [comment]
请使用php7.4以上版本
