### ISSUE TITLE
希望内置商城的功能多一些

### ISSUE THREAD

**Issue by t-o-n-y-w** [Vpay-Collection/VPay#69]
在内置商城里希望添加 其他功能
1.分销
2.会员
3.余额
等等

**Comment by dreamncn** [comment]
内置商城的目的是支付演示以及实现简单的支付功能，适用于很多轻量级的支付场景：付费入群、生成激活码这种。
你所说的这些功能超出了一个轻量级支付场景，不适合在Vpay中实现。
建议使用专业的商城站点搭建。

**Comment by t-o-n-y-w** [comment]
无法安装 一直 提示 loading 这个界面

**Comment by t-o-n-y-w** [comment]
这个能对接到 易支付吗
