### ISSUE TITLE
无法安装 啥情况

### ISSUE THREAD

**Issue by t-o-n-y-w** [Vpay-Collection/VPay#70]
无法安装 啥情况
安装界面 一直处于 loading 这个界面
往下拉 可以看到 填写信息的 但填写后
又跳转到 loading这个界面了

**Comment by dreamncn** [comment]
伪静态的问题吧

**Comment by t-o-n-y-w** [comment]
设置了

**Comment by dreamncn** [comment]
附上F12截图吧

**Comment by t-o-n-y-w** [comment]
伪静态 填写的是
if ( $uri ~* "^(.*)\.php$") {
rewrite ^(.*) /index.php break;
}

location / {
  try_files $uri $uri/ /index.php?$query_string;
}

**Comment by t-o-n-y-w** [comment]
截图
![2023-06-11_123434](https://github.com/Vpay-Collection/VPay/assets/75150168/a5cbc7e9-cbc3-4c59-a20b-fb8ee44ed5c5)

**Comment by dreamncn** [comment]
点开Console

**Comment by t-o-n-y-w** [comment]
lockdown-install.js:1 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
mdb.min.css:1     Failed to load resource: the server responded with a status of 404 (Not Found)
head.jpg:1     Failed to load resource: the server responded with a status of 404 (Not Found)
theme.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
mdb.min.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
font.css:1     Failed to load resource: the server responded with a status of 404 (Not Found)
all.min.css:1     Failed to load resource: the server responded with a status of 404 (Not Found)
install.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
form.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
injected.js:1 [TronLink] TronWeb is already initiated. TronLink will overwrite the current instance
6injected.js:1 Provider initialised
2injected.js:1 Request to wallet/getnodeinfo has been queued
content.js:1 Deprecation warning: tabReply will be removed
(anonymous) @ content.js:1
injected.js:1 TronLink initiated
content.js:1 Deprecation warning: tabReply will be removed
(anonymous) @ content.js:1
index:1 The resource http://aaammm123.com/clean_static/css/mdb.min.css?v=4.0.4 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index:1 The resource http://aaammm123.com/clean_static/css/mdb.min.css?v=4.0.4 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
font.css:1     Failed to load resource: the server responded with a status of 404 (Not Found)
all.min.css:1     Failed to load resource: the server responded with a status of 404 (Not Found)
index:1 The resource http://aaammm123.com/clean_static/css/mdb.min.css?v=4.0.4 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by dreamncn** [comment]
<img width="707" alt="image" src="https://github.com/Vpay-Collection/VPay/assets/37787014/0c892eab-7bf6-47b2-803f-91daeaa475a4">

**Comment by t-o-n-y-w** [comment]
怎么删除

**Comment by t-o-n-y-w** [comment]
伪静态 我只填了
if ( $uri ~* "^(.).php$") {
rewrite ^(.) /index.php break;
}

location / {
try_files $uri $uri/ /index.php?$query_string;
}

**Comment by dreamncn** [comment]
抱歉，`如何删除宝塔面板默认的nginx配置`这不在vpay的讨论范畴之中。
个人认为这是个基本问题，可以通过百度解决。
<img width="130" alt="image" src="https://github.com/Vpay-Collection/VPay/assets/37787014/58487609-dcfa-4989-9983-f146467f95d1">

**Comment by t-o-n-y-w** [comment]
ok 找到了 谢谢
