### ISSUE TITLE
填写支付宝uid 扫码支付异常

### ISSUE THREAD

**Issue by eshao2018** [Vpay-Collection/VPay#8]
1.支付宝的转账接口应该是已经挂了，填写uid扫码支付宝跳转异常连接界面；
2.邮箱发件，无错误日志，打印$re 内容为空，无错误提示。能否增加错误提示。

**Comment by dreamncn** [comment]
1、转账接口在安卓下可用，ios下不可用，目前考虑关闭
2、这个描述不大看得懂，可以举个例子嘛

**Comment by eshao2018** [comment]
正在尝试发送邮件！ 测试失败！具体错误原因请查看上边的日志记录！就是一直提示发送邮件失败

**Comment by dreamncn** [comment]
好的，我把等会更新

**Comment by eshao2018** [comment]
安卓的转账接口也已经挂了 如果是自己的账号扫码是正常的但是提示自己不能给自己转账，  其他号扫码就会提示已停止访问该网页包含不符合规则的内容
