### ISSUE TITLE
同步回调通过returnUrl传递参数无效优先级一直是后台的同步回调地址

### ISSUE THREAD

**Issue by eshao2018** [Vpay-Collection/VPay#9]
大佬 同步通知和异步回调通过参数传递无效，是只响应后台填写的地址吗？另外能不能麻烦大佬把开发文档弄下，发现有些和原版的说明文档不一样

**Comment by dreamncn** [comment]
后台具有app添加功能，不允许通过参数来传递回调地址,遵循一个APP拥有一个固定的回调地址，通过传递额外参数（param）来判断具体是哪个商品
开发文档...写起来太麻烦了...有空我写一下吧...

**Comment by eshao2018** [comment]
好的 了解 谢谢！
